### ISSUE TITLE
`adata.X` contains only zeros for all `sp.datasets`

### ISSUE THREAD

**Issue by maarten-devries** [potulabe/symphonypy#3]
E.g. `adata_ref = sp.datasets.pbmcs_10x_reference()` gives me an AnnData object where the entire `.X` consists of zeros.

**Comment by serjisa** [comment]
Yes, that's not a bug.

We adapted references from the original Symphony repository (https://zenodo.org/record/5090425), and expressions aren't stored at all there, so we decided to fill `adata.X` with zeros (but we keep means and sd's that are necessary for the algorithm).
