### ISSUE TITLE
errors no labels were transfered

### ISSUE THREAD

**Issue by Sirin24** [potulabe/symphonypy#4]
sc.pp.normalize_total(adata, target_sum=1e5)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, batch_key='sample_id', flavor='seurat_v3', layer="counts", n_top_genes=2000, subset=True, span = 1)
sc.pp.scale(adata, max_value=10)
sc.pp.pca(adata, n_comps=50, zero_center=False)
sc.pp.neighbors(adata, use_rep="X_pca")
sc.tl.umap(adata)
sc.tl.leiden(adata)

adata
AnnData object with n_obs × n_vars = 2480956 × 2000
    obs: 'ROIGroup', 'ROIGroupCoarse', 'ROIGroupFine', 'roi', 'organism_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'assay_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'donor_id', 'suspension_type', 'dissection', 'fraction_mitochondrial', 'fraction_unspliced', 'cell_cycle_score', 'total_genes', 'total_UMIs', 'sample_id', 'supercluster_term', 'cluster_id', 'subcluster_id', 'cell_type_ontology_term_id', 'tissue_ontology_term_id', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'leiden'
    var: 'Biotype', 'Chromosome', 'End', 'Gene', 'Start', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm', 'highly_variable_nbatches', 'mean', 'std'
    uns: 'batch_condition', 'citation', 'schema_reference', 'schema_version', 'title', 'log1p', 'hvg', 'pca', 'neighbors', 'umap', 'leiden', 'cluster_id_colors', 'sample_id_colors', 'leiden_colors', 'supercluster_term_colors', 'harmony'
    obsm: 'X_UMAP', 'X_tSNE', 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'distances', 'connectivities'
    

  **then for the next part, am I missing something? I do not see any labels  or umap coordinates that were transfered:**
    
 sample = sc.read_10x_h5(path) 
/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/anndata/_core/anndata.py:1908: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

sample.var_names_make_unique() 

sc.pp.normalize_total(sample, target_sum=1e5)

sc.pp.log1p(sample)

sample
AnnData object with n_obs × n_vars = 3510 × 40090
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'log1p'

sp.tl.map_embedding(adata_query=sample, adata_ref=adata)
348 out of 2000 genes from the reference are missing in the query dataset or have zero std in the reference, their expressions in the query will be set to zero

**why the sample now has 'X_pca_harmony', 'X_pca_harmony_symphony_R'  yet no harmony was used ?**
sample
AnnData object with n_obs × n_vars = 3510 × 40090
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'log1p'
    obsm: 'X_pca_reference', 'X_pca_harmony', 'X_pca_harmony_symphony_R'

**what is the purpose of the ingest step? i do not see any changes**
sp.tl.ingest(adata_query=sample, adata_ref=adata)
/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")

sample
AnnData object with n_obs × n_vars = 3510 × 40090
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'log1p'
    obsm: 'X_pca_reference', 'X_pca_harmony', 'X_pca_harmony_symphony_R'

sp.tl.transfer_labels_kNN(
...     adata_query=sample,
...     adata_ref=adata,
...     ref_labels=["supercluster_term"]
... )

 sample
AnnData object with n_obs × n_vars = 3510 × 40090
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'log1p'
    obsm: 'X_pca_reference', 'X_pca_harmony', 'X_pca_harmony_symphony_R'
    
    
**when I tried to use an rmarkdown, in which i specify in each chunk python and these were the errors:**

sp.tl.ingest(adata_query=sample, adata_ref=adata)
/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/umap/umap_.py:1943: UserWarning: n_jobs value -1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(f"n_jobs value {self.n_jobs} overridden to 1 by setting random_state. Use no seed for parallelism.")
TypeError: float() argument must be a string or a number, not 'csr_matrix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/symphonypy/tools.py", line 238, in ingest
    ing.map_embedding(method)
  File "/home.virtualenvs/r-reticulate/lib64/python3.9/site-packages/scanpy/tools/_ingest.py", line 499, in map_embedding
    self._obsm['X_umap'] = self._umap_transform()
  File "/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/scanpy/tools/_ingest.py", line 488, in _umap_transform
    return self._umap.transform(self._obsm['rep'])
  File "/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/umap/umap_.py", line 3028, in transform 
  indices, dists = self._knn_search_index.query(
  File "/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/pynndescent/pynndescent_.py", line 1696, in query
    query_data = np.asarray(query_data).astype(np.float32, order="C")
ValueError: setting an array element with a sequence.

sp.tl.transfer_labels_kNN(
    adata_query=sample,
    adata_ref=adata,
    ref_labels=["leiden", "supercluster_term"],
)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.virtualenvs/r-reticulate/lib64/python3.9/site-packages/symphonypy/tools.py", line 411, in transfer_labels_kNN
    knn.fit(adata_ref.obsm[ref_basis], adata_ref.obs[ref_labels])
  File "/home/virtualenvs/r-reticulate/lib64/python3.9/site-packages/anndata/_core/aligned_mapping.py", line 196, in __getitem__
    return self._data[key]
KeyError: 'X_pca_harmony'

**Comment by serjisa** [comment]
Hi!

LTDR: follow this tutorial (https://github.com/potulabe/symphonypy/blob/main/notebooks/Symphonypy_without_harmony_tutorial.ipynb) with the **label transfer without prev. Harmony step**.

(a) Sample has `X_pca_harmony` now because you used the way of the mapping without Harmony step on a reference (it's described here: https://github.com/potulabe/symphonypy/blob/main/notebooks/Symphonypy_without_harmony_tutorial.ipynb). Long story short, in your case it's corrected coordinates of the query dataset.

(b) To correctly use ingest in this case, you have to explicitly put the name of dimensionality reduction in your query sample (else it will consider that the coordinates are the same with the reference object), so instead run `sp.tl.ingest(adata_query=sample, adata_ref=adata, use_rep="X_pca_harmony")`.

(c) The same with the kNN classifier — be careful with the default values and put `ref_basis` and `query_basis` explicitly.
